<<<<<<< HEAD
# Generated by Django 3.2.18 on 2023-05-24 05:41
=======
# Generated by Django 3.2.18 on 2023-05-24 05:20
>>>>>>> aa8851d154c0d10e043f1b4308e5f2413011d336

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('stills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stills', '0001_initial'),
>>>>>>> aa8851d154c0d10e043f1b4308e5f2413011d336
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='communities.comment')),
                ('still', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stills.still')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
