# Generated by Django 3.2.18 on 2023-05-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='still',
            name='still_image',
            field=models.FileField(upload_to='stills/'),
        ),
    ]
