# Generated by Django 3.2.12 on 2023-05-19 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='still',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
