# Generated by Django 3.2.18 on 2023-05-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_release_date',
            new_name='movie_released_date',
        ),
    ]
