# Generated by Django 3.2.12 on 2023-05-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='still',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
