# Generated by Django 3.2.12 on 2023-05-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stills', '0002_alter_still_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='still',
            name='like_users',
        ),
    ]
