# Generated by Django 3.2.18 on 2023-05-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stills', '0002_rename_movie_release_date_movie_movie_released_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(max_length=20),
        ),
    ]
